/* Draft preview only. Exact ramp samples come from the generated candidate. */
(async()=>{
const {colors:C,audit:A}=window.LOCATION_STUDY;
const S=await fetch('location-metrics.json').then(r=>{if(!r.ok)throw Error('Metric definitions unavailable');return r.json()});
const params=new URLSearchParams(location.search);
let lang=params.get('lang')==='en'?'en':'th',theme=params.get('theme')==='dark'?'dark':'light';
let family=C.scales.some(s=>s.scaleId===params.get('family'))?params.get('family'):'li.demand';
let n=[3,5,7,9].includes(+params.get('n'))?+params.get('n'):5;
let vision=['normal','deuteranopia','protanopia','gray'].includes(params.get('vision'))?params.get('vision'):'normal';
const $=id=>document.getElementById(id),t=(th,en)=>lang==='th'?th:en;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metric=id=>S.metrics.find(m=>m.id===id),role=id=>C.roles.find(r=>r.id===id),name=id=>metric(id)?.[lang==='th'?'labelTh':'labelEn']||id;
const ramp=(id,th)=>C.scales.find(s=>s.scaleId===id&&s.theme===th);
const english={
 'li.demand':['Purchase occasions per month in the defined business category.','A larger opportunity does not establish sales for a new branch.'],
 'li.supply':['Available service capacity in the same business category and time period.','Store counts alone do not measure capacity or competitive intensity.'],
 'li.market_size':['Total category expenditure in the defined market and period.','Not the revenue that a new branch will capture; avoid double-counting overlapping catchments.'],
 'li.strength':['Evidence of an internal advantage relative to the business strategy.','A qualitative evidence lens; no score or gradient without an explicit, reviewed rubric.'],
 'li.weakness':['Evidence of an internal limitation relative to the business strategy.','A qualitative evidence lens; no automatic conversion from low demand or high cost.'],
 'li.opportunity':['Evidence of a favourable external condition relevant to this business.','An opportunity is a supported hypothesis, not guaranteed demand or sales.'],
 'li.threat':['Evidence of an adverse external condition relevant to this business.','A competitor count is not automatically a threat, nor a hazard probability.'],
 'li.market_share':['Our measured category sales divided by total category sales in the same market and period.','If sales coverage is incomplete, show the limitation. Store count is not sales share.'],
 'li.spending_readiness':['Share of eligible research respondents meeting explicitly defined available-budget AND near-term purchase-intent rules.','Income or wealth does not establish readiness; state survey design, timing and coverage.'],
 'li.demand_growth':['Change from the comparable previous-period demand baseline. Zero means unchanged.','A zero baseline makes percentage growth undefined. Positive growth can exceed 100%.'],
 'li.accessibility':['Share of target demand weight reachable within a declared travel-time threshold.','State travel mode, time of day, network quality and target-demand evidence.'],
 'li.competitive_pressure':['Comparable rival capacity relative to the relevant category demand.','Capacity estimates are proxies unless verified. Ratios can exceed 100%.'],
 'li.service_gap':['Demand minus comparable capacity, normalized by demand. Zero means modelled balance.','Demand and capacity must use compatible units. A gap is not guaranteed profitable opportunity.'],
 'li.cannibalization':['Expected sales transferred from our existing branches, relative to proposed-branch sales.','A modelled transfer, not observed behaviour. Separate own network from competitors.'],
 'li.occupancy_cost':['Occupancy cost relative to sales for the same site and period.','Declare observed versus forecast inputs; the ratio can exceed 100%.'],
 'li.unit_economics':['Operating profit relative to sales for the same branch and period. Zero means operating break-even.','This is operating margin, not a complete investment return or permission to open.']
};
const marker=(id,th=theme)=>{let m=metric(id),v=role(id)[th],shape=m.nonColorCue.shape;let paths={circle:'<circle cx="20" cy="20" r="17"/>',square:'<rect x="3" y="3" width="34" height="34" rx="3"/>',diamond:'<path d="M20 2L38 20L20 38L2 20Z"/>',triangle:'<path d="M20 2L38 36H2Z"/>',hexagon:'<path d="M11 3H29L38 20L29 37H11L2 20Z"/>',pentagon:'<path d="M20 2L38 15L31 37H9L2 15Z"/>',cross:'<path d="M13 2H27V13H38V27H27V38H13V27H2V13H13Z"/>'};return `<svg class="role-marker" viewBox="0 0 40 40" data-shape="${shape}" aria-hidden="true"><g fill="${v.hex}" stroke="${v.labelHex}" stroke-width="1.3">${paths[shape]||paths.circle}</g><text x="20" y="${shape==='triangle'?27:24}" fill="${v.labelHex}" text-anchor="middle">${esc(m.recommendedMarker.text)}</text></svg>`};
const rgb=h=>h.match(/\w\w/g).map(x=>parseInt(x,16)/255);
const lum=h=>rgb(h.replace('#','')).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{let x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const ink=h=>contrast(h,'#000000')>=contrast(h,'#FFFFFF')?'#000000':'#FFFFFF';
const strip=(list,continuous=false)=>`<div class="strip ${continuous?'continuous':''} perception" aria-hidden="true">${list.map(h=>`<i style="background:${h}"></i>`).join('')}</div>`;
function anchors(s){return `<div class="anchors">${s.anchors.map((h,i)=>`<div class="anchor"><i class="perception" style="--chip:${h}"></i><div><small>${s.kind==='diverging'?[t('ลบ','Negative'),t('ศูนย์','Zero'),t('บวก','Positive')][i]:[t('ต่ำ','Low'),t('กลาง','Mid'),t('สูง','High')][i]}</small><code>${h}</code></div></div>`).join('')}</div>`}
function updateURL(){let p=new URLSearchParams({lang,theme,family,n,vision});history.replaceState(null,'',`?${p}${location.hash}`)}
function drawRoles(){
 $('hero-sample').innerHTML=['li.demand','li.supply','li.market_size','li.threat'].map(id=>{let r=role(id),v=r[theme];return `<div class="hero-tile perception" style="background:${v.hex};color:${v.labelHex}"><b>${esc(metric(id).recommendedMarker.text)}</b><span>${esc(name(id))}</span></div>`}).join('');
 $('role-grid').innerHTML=C.roles.map(r=>`<article class="role-card"><div class="paired-swatch perception">${['light','dark'].map(th=>`<div style="background:${r[th].hex};color:${r[th].labelHex}">${marker(r.id,th)}<code>${r[th].hex}</code></div>`).join('')}</div><h3>${esc(name(r.id))}</h3><small>${esc(r[lang==='th'?'colorNameTh':'colorNameEn'])} · ${esc(({quiet:t('สงบ','Quiet'),supporting:t('ประกอบ','Supporting'),focused:t('เน้น','Focused'),urgent:t('เร่งด่วน','Urgent')})[r.chromaRole]||r.chromaRole)}</small></article>`).join('');
}
function mapSVG(s,id){const data=[0,7,23,45,64,91,8,19,44,60,83,100,12,30,55,null,86,96,3,25,50,74,0,99];let list=s.classes[n],div=s.kind==='diverging';return `<svg class="sample-map perception" viewBox="0 0 330 224" role="img" aria-label="${t('แผนผังตัวเลขสมมติ','Synthetic value diagram')}"><defs><pattern id="na-${id}" width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill="${s.theme==='dark'?'#303C3F':'#E7ECE6'}"/><path d="M0 6L6 0" stroke="${s.theme==='dark'?'#BCC6C0':'#64726D'}" stroke-width="1"/></pattern></defs>${data.map((v,i)=>{let value=v===null?null:div?2*v-100:v,idx=v===null?null:Math.min(n-1,Math.floor(v*n/100)),h=idx===null?null:list[idx],zero=value===0,x=3+(i%6)*55,y=3+Math.floor(i/6)*55;return `<g data-cell="${i}" data-value="${value}" data-index="${idx}" data-fill="${h}"><rect x="${x}" y="${y}" width="49" height="49" rx="3" fill="${h||`url(#na-${id})`}" stroke="${zero?(s.theme==='dark'?'#F1F4EF':'#182327'):(s.theme==='dark'?'#52605D':'#BAC6C0')}" stroke-width="${zero?3:1}"/><text x="${x+24.5}" y="${y+28}" fill="${h?ink(h):(s.theme==='dark'?'#FFFFFF':'#000000')}" text-anchor="middle">${value===null?'N/A':value}</text></g>`}).join('')}</svg>`}
function lab(){
 let l=ramp(family,'light'),d=ramp(family,'dark'),m=metric(family),r=role(family);
 $('lab-context').innerHTML=`<div class="role-label">${marker(family)}<h3>${esc(name(family))}</h3></div><p>${esc(lang==='th'?m.highMeaning:english[family][0])}</p>`;
 let specs=[{s:l,title:t('พื้นสว่าง','Light canvas'),tag:'LIGHT / REFERENCE',key:'light'}, {s:{...l,theme:'dark'},title:t('พื้นมืด · HEX เดิม','Dark / same HEX'),tag:'DARK / DIRECT REUSE',key:'raw'}, {s:d,title:t('พื้นมืด · ใช้สูตร','Dark / adapted'),tag:'DARK / DERIVED RENDITION',key:'derived'}];
 $('theme-comparison').innerHTML=specs.map(({s,title,tag,key})=>{let cv=C.canvases[s.theme],min=Math.min(...s.lut41.map(h=>contrast(h,cv)));return `<article class="theme-card" data-theme="${s.theme}" style="background:${cv}"><p class="tag">${tag}</p><h3>${title}</h3>${mapSVG(s,key)}${strip(s.lut41,true)}${strip(s.classes[n])}<div class="scale-labels"><span>${s.kind==='diverging'?'−100':'0'}</span><span>${s.kind==='diverging'?'0':50}</span><span>100</span></div>${anchors(s)}<div class="contrast">${t('คอนทราสต์ต่ำสุดกับพื้น','Lowest fill/canvas contrast')} ${min.toFixed(2)}:1</div><p>${s.kind==='diverging'?t('ค่าศูนย์ใช้สีกลาง พร้อมกรอบและตัวเลข ไม่ต้องเดาจากสี','Zero uses the neutral midpoint, with a boundary and a number.'):key==='raw'?t('ปลายเข้มจากธีมสว่างอาจกลืนพื้นมืด แม้บางสีจะใช้ได้','Dark endpoints from the light theme may disappear into a dark canvas.'):s.theme==='dark'?t('ค่าสูงสว่างขึ้น สีประจำตัวแปรคงอยู่ที่หัวและท้าย','Higher values become lighter; semantic hue remains at both ends.'):t('ค่าสูงเข้มขึ้น สีอ่อนยังต้องมีขอบแยกพื้นที่','Higher values become darker; pale cells retain visible boundaries.')}</p><div class="legend-lines">${s.classes[n].map((h,i)=>{let lo=Math.ceil(i*(s.kind==='diverging'?200:100)/n)-(s.kind==='diverging'?100:0),hi=i===n-1?100:Math.ceil((i+1)*(s.kind==='diverging'?200:100)/n)-(s.kind==='diverging'?100:0)-1;return `<span>${i+1}: ${lo}…${hi}</span>`}).join('')}</div></article>`}).join('');
 $('formula').innerHTML=`<p>${t('สร้างค่าสีสองธีมไว้ล่วงหน้าแล้วบันทึก HEX ที่แน่นอน สูตรเป็นจุดตั้งต้นที่ต้องตรวจทั้งชุด ไม่ให้แต่ละเครื่องมือปรับเองตามใจ','Generate both theme renditions in advance and store the exact HEX values. The formula is a tested starting point, not permission for each tool to improvise.')}</p><ul><li>${t('สีประจำบทบาท: คง hue ปรับ lightness และลด chroma พร้อมตรวจสีคู่ที่ใช้ร่วมกัน','Role accents: preserve hue; adjust lightness and chroma, then check co-displayed pairs.')}</li><li>${t('Sequential: รักษาสามสีหลัก แต่ให้ความสว่างเรียงตามปริมาณบนพื้นนั้น','Sequential: retain three deliberate anchors with a consistent lightness order on each canvas.')}</li><li>${t('Diverging: รักษาความหมายลบ–ศูนย์–บวก และตรวจแขนทั้งสองแยกกัน','Diverging: preserve negative–zero–positive meaning and check both arms independently.')}</li><li>${t('อย่าใช้สี fill เป็นสีตัวหนังสือโดยตรง เลือกสีข้อความจาก contrast ที่คำนวณจริง','Do not use fill colours directly as text. Select label ink from measured contrast.')}</li></ul><p><a href="location-colors.json" download>${t('ดาวน์โหลดสูตรละเอียด + ค่า HEX ที่ได้','Download exact formula definitions and derived HEX values')}</a></p>`;
}
function library(){
 $('scale-grid').innerHTML=S.metrics.filter(m=>m.useScale!=='none').map(m=>{let s=ramp(m.id,theme);return `<article class="family-card" data-family="${m.id}"><p class="kind">${s.kind.toUpperCase()} · ${theme.toUpperCase()}</p><div class="role-label">${marker(m.id)}<h3>${esc(name(m.id))}</h3></div><p>${esc(lang==='th'?m.highMeaning:english[m.id][0])}</p>${strip(s.lut41,true)}${strip(s.classes[n])}${anchors(s)}<button class="open-metric" data-metric="${m.id}">${t('ทดลองชุดนี้','Try this scale')}</button></article>`}).join('');
 $('swot-grid').innerHTML=S.metrics.filter(m=>m.useScale==='none').map(m=>`<article class="swot-card">${marker(m.id)}<h3>${esc(name(m.id))}</h3><p>${esc(lang==='th'?m.example.textTh:english[m.id][0])}</p><p>${t('มุมมองหลักฐาน · ไม่ใช่สเกลคะแนน','Evidence lens · No quantitative ramp')}</p></article>`).join('');
 document.querySelectorAll('.open-metric').forEach(b=>b.addEventListener('click',()=>{family=b.dataset.metric;$('metric').value=family;lab();updateURL();location.hash='lab'}));
}
function audit(){
 let roleFails=A.summary.rawLightReuseDarkFails.length,allPairs=A.rolePairs.filter(p=>p.theme===theme),minDark=Math.min(...C.roles.map(r=>r.dark.canvasContrast));
 $('audit-summary').innerHTML=`<div class="audit-stats"><div class="audit-stat"><b>16 / 16</b><span>${t('สีประจำบทบาทไม่ซ้ำ HEX ในแต่ละธีม','Unique role HEX values per theme')}</span></div><div class="audit-stat"><b>${roleFails} → 0</b><span>${t('บทบาทบนพื้นมืดที่ต่ำกว่า 3:1','Dark role accents below 3:1')}</span></div><div class="audit-stat"><b>${A.coverage.lutSamples}</b><span>${t('สีระหว่างทางผ่านข้อห้ามเชิงตัวเลข','LUT samples pass numerical hue exclusions')}</span></div><div class="audit-stat"><b>${minDark.toFixed(2)}:1</b><span>${t('คอนทราสต์ต่ำสุดของสีประจำบทบาทบนพื้นมืด','Minimum dark role accent contrast')}</span></div></div><p class="note">${t('ผ่านลำดับความสว่างทั้ง 24 สเกล แต่ยังมีสีช่วง amber/clay ที่ควรตัดสินด้วยสายตา '+A.summary.clayWarningSamples+' ตัวอย่าง และยังมีคู่สีใกล้กันด้านล่าง จึงไม่รับรองว่าแยกทั้ง 16 บทบาทได้ด้วยสีล้วน','All 24 scales preserve lightness order. '+A.summary.clayWarningSamples+' amber/clay samples still need visual judgement, and close pairs remain below. This does not certify 16 colour-only distinctions.')}</p>`;
 $('collision-results').innerHTML=['normal','deuteranopia','protanopia'].map(mode=>{let pairs=allPairs.filter(p=>p.mode===mode).sort((a,b)=>a.deltaE-b.deltaE),count=pairs.filter(p=>p.screeningFlag).length;return `<div class="audit-group"><h3>${mode==='normal'?t('การมองเห็นปกติ','Normal vision'):mode} · ${theme}</h3><p class="note">${t('คู่ที่ใกล้ที่สุด 4 คู่ · คู่ที่ควรตรวจเพิ่ม','Four nearest pairs · Pairs flagged for review')}: ${count} / 120</p><div class="collision-list">${pairs.slice(0,4).map(p=>`<article class="collision-item"><div class="pair-dots ${mode==='normal'?'':'vision-'+mode}"><span class="perception">${p.roles.map(id=>`<i style="background:${role(id)[theme].hex}"></i>`).join('')}</span><strong>${p.roles.map(name).map(esc).join(' / ')}</strong></div><p>ΔE OK × 100 = ${p.deltaE.toFixed(2)} · ${t('ใช้ชื่อและเครื่องหมายร่วม แยก panel เมื่อต้องเทียบ','Keep names and markers; separate panels when comparing')}</p></article>`).join('')}</div></div>`}).join('')+`<p class="note">${t('ใช้เกณฑ์คัดกรอง ΔE 8 สำหรับปกติ และ 5 สำหรับภาพจำลอง ตัวเลขนี้เป็นเกณฑ์ทดลองของชุดนี้ ไม่ใช่มาตรฐานรับรอง อ่านผลทุกคู่และกลุ่มที่ใช้ร่วมกันได้ในไฟล์ JSON','Screening cutoffs are ΔE 8 for normal vision and 5 for simulations. These are study heuristics, not certification standards. JSON includes every pair and co-display group.')}</p>`;
}
function guide(){
 if(!$('readme-link')){const a=document.createElement('a');a.id='readme-link';a.href='README.md';a.download='README.md';document.querySelector('.downloads').prepend(a)}
 $('readme-link').textContent=t('คำแนะนำและผลทดสอบ','Recommendation and test summary');
 if(!$('cross-aliases')){
 const d=document.createElement('details');d.id='cross-aliases';$('collision-results').after(d);
 }
 $('cross-aliases').innerHTML=`<summary>${t('เทียบกับสเกลเดิม 20 ประเภท: ส่วนที่ใช้ร่วมกัน','Compared with the original 20 families: deliberate reuse')}</summary><div class="details-body"><p>${t('มี 4 สเกลธีมสว่างที่ใช้เส้นทางสีเดียวกับชุด Story เดิม จึงไม่ได้อ้างว่าทั้งระบบไม่มีสีซ้ำ ถ้าต้องเทียบข้ามประเภท ให้แยก panel พร้อมชื่อและหน่วย','Four light-theme scales share an existing Story colour route. The complete system is not globally colour-unique. Compare cross-domain metrics in separate panels with names and units.')}</p><ul>${A.crossStoryComparison.exactVisualAliases.map(x=>`<li>${esc(name(x.id))} → ${x.aliases.map(a=>esc(a.scaleId)).join(', ')} · ${x.theme}</li>`).join('')}</ul><p>${t('สีประจำบทบาท 16 ค่าไม่ซ้ำ HEX แต่ความต่างของทั้งสเกลเป็นอีกเรื่องหนึ่ง ผลเทียบกับชุดเดิมทุกคู่อยู่ในไฟล์ผลตรวจ','The 16 role accents have unique HEX values; whole-ramp distinction is a separate question. The audit file includes every comparison against the original families.')}</p></div>`;
 $('metric-guide').innerHTML=S.metrics.map((m,i)=>`<details><summary>${String(i+1).padStart(2,'0')} · ${esc(name(m.id))}${lang==='th'?' / '+esc(m.labelEn):''}</summary><div class="details-body semantic-copy"><code>${m.id}</code>${lang==='th'?`<p><strong>หน่วย:</strong> ${esc(m.unit)}</p><p><strong>ความหมาย:</strong> ${esc(m.highMeaning)}</p><p><strong>ขอบเขตหลักฐาน:</strong> ${esc(m.evidenceBoundary)}</p>`:`<p>${esc(english[m.id][0])}</p><p>${esc(english[m.id][1])}</p>`}<p class="metric-source">${t('สัญลักษณ์','Marker')}: ${esc(m.recommendedMarker.text)} · ${t('ชื่อย่อ','Short code')}: ${esc(m.nonColorCue.shortLabel)} · ${m.useScale}</p></div></details>`).join('');
}
function render(){document.documentElement.lang=lang;document.documentElement.dataset.theme=theme;document.body.className='vision-'+vision;document.querySelectorAll('[data-th]').forEach(e=>e.innerHTML=e.dataset[lang]);$('language').value=lang;$('theme').value=theme;$('classes').value=n;$('vision').value=vision;$('metric').innerHTML=S.metrics.filter(m=>m.useScale!=='none').map(m=>`<option value="${m.id}">${esc(name(m.id))}</option>`).join('');$('metric').value=family;drawRoles();lab();library();audit();guide();updateURL()}
 $('language').addEventListener('change',e=>{lang=e.target.value;render()});$('theme').addEventListener('change',e=>{theme=e.target.value;render()});$('metric').addEventListener('change',e=>{family=e.target.value;lab();updateURL()});$('classes').addEventListener('change',e=>{n=+e.target.value;lab();library();updateURL()});$('vision').addEventListener('change',e=>{vision=e.target.value;document.body.className='vision-'+vision;updateURL()});
 render();
})().catch(e=>{document.querySelector('main').insertAdjacentHTML('afterbegin','<p role="alert">โหลดชุดทดลองไม่สำเร็จ / Preview data could not load. Please reload.</p>');console.error(e)});
