/* Candidate review only. Every rendered data colour comes from data.js. */
(() => {
 const D=window.COLOR_STUDY;if(!D){document.querySelector('#comparison').textContent='Candidate data not available.';return;}
 const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const p=new URLSearchParams(location.search),S={lang:p.get('lang')==='en'?'en':'th',theme:p.get('theme')==='dark'?'dark':'light',family:p.get('family')||'water',n:[3,5,7,9].includes(+p.get('n'))?+p.get('n'):7,vision:p.get('vision')||'normal'};
 const ids=D.candidate.scales.filter(r=>r.theme==='light').map(r=>r.scaleId);if(!ids.includes(S.family))S.family='water';
 const en={activity:'Activity','density.area':'Density · per area',heat:'Heat',risk:'Risk',price:'Price',age:'Age','density.household':'Density · per household',growth:'Growth',confidence:'Confidence',count:'Count',water:'Water','density.capita':'Density · per capita',built:'Built form',duration:'Duration',balance:'Balance',delta:'Change',tradeoff:'Trade-off',flow:'Net flow',sentiment:'Sentiment',anomaly:'Anomaly'};
 const why={
 activity:['ให้กิจกรรมมีพลังแบบเย็น แยกจากความเสี่ยงและความร้อน','Cool energy separates activity from heat and risk.'],
 'density.area':['คงโทนส้มและระบุตัวหารพื้นที่ ใช้ความร้อนของสีสื่อความหนาแน่น','Orange density with an explicit area denominator.'],
 heat:['ใช้เหลืองและแดงส้มสื่อความร้อน ระดับความสว่างเรียงตามธีม','Yellow and vermilion keep heat clearly warm; lightness follows the theme.'],
 risk:['ใช้แดงและคอรัลแยกความเสี่ยงจากกิจกรรม ค่าสูงเข้มขึ้นบนพื้นสว่าง และสว่างขึ้นบนพื้นมืด','Red and coral separate risk from activity. High values darken on light and brighten on dark backgrounds.'],
 price:['เขียวในบริบทมูลค่า สีกลางมิ้นต์ฟ้าช่วยแยกจากการเติบโต','A green value context, with a mint-cyan middle distinct from growth.'],
 age:['ใช้เฉดที่นิ่งและมีน้ำหนัก อายุที่มากกว่าไม่แปลว่าดีหรือแย่กว่า','A restrained temporal palette. Older does not mean better or worse.'],
 'density.household':['ใช้ชมพูกุหลาบกับแดงส้มตามธีม พร้อมระบุตัวหารครัวเรือน','Rose and warm orange-red roles, with lightness adapted to the theme and the household denominator stated.'],
 growth:['ใช้เขียวเหลืองคู่เขียวใบไม้ สื่อการเติบโตโดยไม่ตัดสินผลกระทบ','Yellow-green and leaf green describe growth; growth is not automatically beneficial.'],
 confidence:['ความเชื่อมั่นของข้อมูลต้องมีคำอธิบาย ไม่ใช้สีแทนความถูกต้อง','Confidence needs a definition; colour cannot establish correctness.'],
 count:['น้ำเงินหมึกสำหรับปริมาณทั่วไป แยกจากความหมายเฉพาะของน้ำ','Editorial navy for general magnitude, separate from aquatic colour.'],
 water:['สีกลางอยู่ในตระกูลน้ำ ไม่มีเขียวมะนาวมาครองภาพ','An aquatic middle, without lime taking over the map.'],
 'density.capita':['ใช้แซลมอนคู่กุหลาบ คงความร้อนและระบุตัวหารประชากร','Salmon and rose stay warm, with an explicit population denominator.'],
 built:['พีชและทองสำหรับความเข้มข้นสิ่งปลูกสร้าง ระบุว่าเป็น footprint ความสูง หรือสัดส่วนปกคลุม; ไม่ถือว่าเป็น density โดยอัตโนมัติ','Peach and gold for defined built form: footprint, height or coverage. This is not automatically a density ratio.'],
 duration:['ลดความอิ่มสีสำหรับเวลา แยกจากจำนวนรวมและน้ำ','Restrained time colours, separate from general count and water.'],
 balance:['จุดกลางคือสมดุลที่ระบุ เช่น สุทธิเป็นศูนย์ ปลายทั้งสองมีน้ำหนักใกล้กัน','The centre is a declared balance, such as net zero; both sides carry comparable weight.'],
 delta:['จุดกลางคือไม่เปลี่ยนจากฐานเดียวกัน ลบและบวกไม่ได้แปลว่าแย่และดีเสมอไป','Zero change from the same baseline; negative and positive are not inherently bad and good.'],
 tradeoff:['จุดกลางต้องเป็นเงื่อนไขอ้างอิงที่มีความหมาย ไม่ใช่ค่ากลางที่เดาขึ้น','The centre needs a meaningful reference condition, not an invented compromise.'],
 flow:['แยกสุทธิออกกับสุทธิเข้า โดยศูนย์คือสมดุลการไหล','Separate net outflow and net inflow around zero balance.'],
 sentiment:['จุดกลางเป็นความคิดเห็นเป็นกลางตามวิธีวัด แยกจากไม่มีคำตอบ','The midpoint is measured neutrality, separate from no response.'],
 anomaly:['แยกต่ำกว่าและสูงกว่าค่าอ้างอิง ความผิดปกติไม่ได้แปลว่าอันตรายเสมอไป','Separate below and above a defined reference. An anomaly is not automatically dangerous.']};
 const t=(th,en)=>S.lang==='th'?th:en;
 const record=(kind,id=S.family)=>D[kind].scales.find(r=>r.scaleId===id&&r.theme===S.theme);
 const name=id=>S.lang==='en'?en[id]:(id==='built'?'ความเข้มข้นสิ่งปลูกสร้าง':record('candidate',id).label);
 const cols=r=>r.classes[String(S.n)];
 const ink=hex=>{const a=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]>.179?'#000000':'#FFFFFF';};
 function strip(a,continuous=false){return `<div class="strip perception${continuous?' continuous':''}">${a.map((v,i)=>`<i style="background:${esc(v)}" title="${i+1}: ${esc(v)}"></i>`).join('')}</div>`;}
 function anchorHTML(r){return `<div class="anchors">${r.anchors.map((v,i)=>`<div class="anchor"><i class="perception" style="--chip:${v}"></i><div><small>${r.kind==='sequential'?[t('หัว','Start'),t('กลาง','Middle'),t('ท้าย','End')][i]:[t('ฝั่งลบ','Negative'),t('จุดอ้างอิง','Reference'),t('ฝั่งบวก','Positive')][i]}</small><code>${v}</code></div></div>`).join('')}</div>`;}
 function syncURL(){const u=new URL(location.href);for(const[k,v]of Object.entries(S))u.searchParams.set(k,v);history.replaceState(null,'',u);}
 function palette(){const ps=D.candidate.supportingPalette,colour=id=>ps.find(s=>s.id===id)?.hex;const paper=colour('paper'),navy=colour('navy'),coral=colour('coral'),mint=colour('mint'),leaf=colour('leaf'),rose=colour('rose'),butter=D.candidate.scales.find(r=>r.scaleId==='heat'&&r.theme==='light').anchors[0];
  $('#palette').innerHTML=ps.map(s=>`<div class="swatch"><div class="swatch-colour" style="background:${s.hex}"></div><h3>${esc(s.name.split(' / ')[S.lang==='th'?1:0]||s.name)}</h3><code>${s.hex}</code></div>`).join('');
  $('#hero-art').innerHTML=`<svg viewBox="0 0 520 420" role="img" aria-label="Navy, butter and coral editorial composition"><rect width="520" height="420" fill="${navy}"/><path d="M0 308C126 184 196 400 350 220S470 68 520 115V420H0Z" fill="${coral}"/><circle cx="406" cy="104" r="46" fill="${butter}"/><text x="38" y="150" fill="${butter}" font-family="Arvo,serif" font-weight="700" font-size="99">Story.</text><text x="40" y="195" fill="${butter}" font-family="Mono,monospace" font-size="13" letter-spacing="3">THREE COLOURS, WITH INTENT</text><path d="M44 332H191M44 352H152M44 372H116" stroke="${navy}" stroke-width="9"/><text x="363" y="383" fill="${navy}" font-family="Mono,monospace" font-size="15">STUDY 01</text></svg>`;
  const arts=[
   {label:t('หนักแน่น + สด + เบา','Weight + energy + space'),desc:t('น้ำเงินหมึก / คอรัล / เหลืองอ่อน','Navy / coral / pale yellow'),svg:`<rect width="400" height="300" fill="${butter}"/><circle cx="292" cy="96" r="77" fill="${coral}"/><text x="22" y="102" fill="${navy}" font-family="Arvo" font-weight="700" font-size="73">Good</text><text x="22" y="178" fill="${navy}" font-family="Arvo" font-weight="700" font-size="73">data.</text><path d="M26 240H372" stroke="${navy}" stroke-width="6"/>`},
   {label:t('พื้นที่หายใจ + สีตัด','A quiet ground + contrast'),desc:t('กระดาษ / ใบไม้ / กุหลาบ','Paper / leaf / rose'),svg:`<rect width="400" height="300" fill="${paper}"/><path d="M195 266C202 176 108 158 87 66C191 58 242 133 204 191C250 83 295 86 333 48C359 151 288 216 213 213" fill="${leaf}"/><circle cx="211" cy="74" r="35" fill="${rose}"/><circle cx="148" cy="181" r="26" fill="${rose}"/><text x="24" y="276" fill="${leaf}" font-family="Mono" font-size="19">Room to grow.</text>`},
   {label:t('เย็นสองระดับ + จุดเด่นอุ่น','Cool depth + a warm accent'),desc:t('น้ำเงินหมึก / มิ้นต์ / คอรัล','Navy / mint / coral'),svg:`<rect width="400" height="300" fill="${navy}"/><path d="M-20 174Q80 66 180 174T420 174" fill="none" stroke="${mint}" stroke-width="50"/><path d="M-20 261Q80 153 180 261T420 261" fill="none" stroke="${mint}" stroke-width="50"/><circle cx="307" cy="66" r="39" fill="${coral}"/>`}
  ];$('#recipes').innerHTML=arts.map(a=>`<div class="recipe"><div class="recipe-art"><svg viewBox="0 0 400 300" preserveAspectRatio="xMidYMid slice" role="img" aria-label="${esc(a.desc)}">${a.svg}</svg></div><p><strong>${a.label}</strong>${a.desc}</p></div>`).join('');
 }
 const points=Array.from({length:7},(_,y)=>Array.from({length:9},(_,x)=>[18+x*53+(x===0||x===8?0:Math.sin(x*7+y*19)*9),18+y*54+(y===0||y===6?0:Math.cos(x*13+y*8)*9)]));
 function cells(r){return Array.from({length:48},(_,i)=>{const x=i%8,y=Math.floor(i/8);let u=Math.max(0,Math.min(1,.49+.23*Math.sin(x*.91+y*1.43)+.19*Math.cos(x*1.54-y*.82)));if(i===0)u=0;if(i===47)u=1;if(i===20)u=.5;const missing=[7,39].includes(i),value=r.kind==='diverging'?Math.round((u*2-1)*100):Math.round(u*100),idx=Math.max(0,Math.min(S.n-1,Math.floor((r.kind==='diverging'?(value+100)/200:value/100)*S.n)));const poly=[points[y][x],points[y][x+1],points[y+1][x+1],points[y+1][x]],cx=poly.reduce((a,p)=>a+p[0],0)/4,cy=poly.reduce((a,p)=>a+p[1],0)/4;return {i,value:missing?null:value,colour:missing?r.noData:cols(r)[idx],index:idx,poly,cx,cy};});}
 function map(r,key){const cs=cells(r),txt=t('ตัวอย่างพื้นที่สมมติ สีและค่ามีตารางประกอบ','Synthetic areas, with numerical labels and an accompanying table');return `<svg class="map perception" viewBox="0 0 460 365" role="img" aria-label="${txt}"><defs><pattern id="missing-${key}" width="7" height="7" patternUnits="userSpaceOnUse"><rect width="7" height="7" fill="${r.noData}"/><path d="M-2 2L2-2M0 7L7 0M5 9L9 5" stroke="${r.zeroOutline}" stroke-width="1"/></pattern></defs>${cs.map(c=>`<g><polygon points="${c.poly.map(p=>p.map(n=>n.toFixed(1)).join(',')).join(' ')}" fill="${c.value===null?`url(#missing-${key})`:c.colour}" stroke="${c.value===0?r.zeroOutline:r.canvas}" stroke-width="${c.value===0?3:1.5}"><title>${c.i+1}: ${c.value===null?'No data':c.value} · ${c.colour}</title></polygon><text x="${c.cx}" y="${c.cy+4}" text-anchor="middle" font-family="Mono,monospace" font-size="10" font-weight="400" fill="${ink(c.colour)}">${c.value===null?'N/A':c.value}</text></g>`).join('')}</svg>`;}
 function compare(){const a=record('baseline'),b=record('candidate'),div=b.kind==='diverging';$('#family-context').innerHTML=`<h3>${name(S.family)}</h3><p>${esc(why[S.family][S.lang==='th'?0:1])}</p><p>${div?t('ตัวอย่าง −100 ถึง +100 · จุดอ้างอิง 0 · แบ่งช่วงเท่ากัน; ช่วงกลางคร่อม 0','Specimen −100 to +100 · reference 0 · equal intervals; the central class spans zero'):t('ดัชนีสมมติ 0–100 · ค่าต่ำ → ค่าสูง · แบ่งช่วงเท่ากัน','Synthetic index 0–100 · low → high · equal intervals')}</p>`;
  $('#comparison').innerHTML=[['baseline',a,'LDS 0.9.6',t('ชุดปัจจุบัน','Current')],['candidate',b,'STORY · CANDIDATE',t('ชุดเสนอใหม่','Proposed')]].map(([key,r,tag,title])=>`<article class="compare-card"><p class="tag">${tag}</p><h3>${title}</h3>${map(r,key)}${strip(r.lut,true)}${strip(cols(r))}<div class="scale-labels"><span>${div?'−100':t('0 · ต่ำ','0 · low')}</span>${div?'<span>0</span>':''}<span>${div?'+100':t('100 · สูง','100 · high')}</span></div>${anchorHTML(r)}</article>`).join('');
  const c1=cells(a),c2=cells(b);const lo=div?-100:0,span=div?200:100;const bins=Array.from({length:S.n},(_,i)=>({low:Math.ceil(lo+i*span/S.n),high:i===S.n-1?lo+span:Math.ceil(lo+(i+1)*span/S.n)-1}));$('#specimen-table').innerHTML=`<p>${t('ข้อมูลตัวอย่างเป็นจำนวนเต็ม ช่วงด้านล่างรวมค่าหัวและท้าย','Specimen values are integers. Both bounds below are inclusive.')}</p><table><thead><tr><th>${t('ระดับ','Class')}</th><th>${t('ช่วงค่าจำนวนเต็ม','Integer range')}</th><th>LDS 0.9.6</th><th>Story</th></tr></thead><tbody>${bins.map((v,i)=>`<tr><td>${i+1}</td><td>${v.low} … ${v.high}</td><td><code>${cols(a)[i]}</code></td><td><code>${cols(b)[i]}</code></td></tr>`).join('')}</tbody></table><table><thead><tr><th>${t('พื้นที่','Area')}</th><th>${t('ค่า','Value')}</th><th>LDS 0.9.6</th><th>Story</th></tr></thead><tbody>${c1.map((c,i)=>`<tr><td>${i+1}</td><td>${c.value??'N/A'}</td><td><span class="table-dot" style="--chip:${c.colour}"></span><code>${c.colour}</code></td><td><span class="table-dot" style="--chip:${c2[i].colour}"></span><code>${c2[i].colour}</code></td></tr>`).join('')}</tbody></table>`;
 }
 function collisions(){const groups=[{label:t('กิจกรรม · ความหนาแน่น · ความเสี่ยง','Activity · density · risk'),ids:['activity','density.area','risk']},{label:t('น้ำ · จำนวนรวม · ระยะเวลา','Water · count · duration'),ids:['water','count','duration']},{label:t('ความหนาแน่นและสิ่งปลูกสร้าง: โทนร้อนที่แยกบทบาท','Density and built form: distinct warm roles'),ids:['density.area','density.capita','density.household','built']}];$('#collisions').innerHTML=groups.map(g=>`<div class="pair-group"><h3>${g.label}</h3><div class="pair-grid ${g.ids.length===4?'four':''}">${g.ids.map(id=>`<article class="pair-card"><h4>${name(id)}</h4><div class="pair-row"><small>0.9.6</small>${strip(cols(record('baseline',id)))}</div><div class="pair-row"><small>STORY</small>${strip(cols(record('candidate',id)))}</div><p>${esc((record('candidate',id)[S.lang==='th'?'previewDesignNote':'previewDesignNoteEn']||'').replaceAll('→','·'))}</p></article>`).join('')}</div></div>`).join('');}
 function library(){$('#all-families').innerHTML=ids.map(id=>{const r=record('candidate',id),old=record('baseline',id);return `<article class="family-card"><button class="family-title" data-family="${id}">${name(id)} ↗</button><div class="kind">${r.kind.toUpperCase()} · ${id} · ${S.theme.toUpperCase()}</div><p>${esc(why[id][S.lang==='th'?0:1])}</p><div class="pair-row"><small>0.9.6</small>${strip(cols(old))}</div><div class="pair-row"><small>STORY</small>${strip(r.lut,true)}${strip(cols(r))}</div>${anchorHTML(r)}<details><summary>${t('ดูสีทั้ง 41 ขั้น','Inspect all 41 samples')}</summary><div class="details-body sample-codes">${r.lut.map((v,i)=>`${i}: ${v}`).join(' · ')}</div></details></article>`;}).join('');}
 function quality(){const a=D.audit,n=a.numerical||{};$('#quality').innerHTML=`<div class="quality-metrics"><div><strong>${a.families||20}</strong><span>${t('ประเภทข้อมูล','families')}</span></div><div><strong>${a.records||40}</strong><span>${t('ชุดสีสองธีม','theme records')}</span></div><div><strong>${a.lutSamples||1640}</strong><span>${t('ค่าสีที่ตรวจ','LUT samples checked')}</span></div></div><ul><li>${t('หัว/กลาง/ท้ายตรงกับ LUT','Anchors match LUT')}: ${n.allThreeAnchorsExact?'PASS':'REVIEW'}</li><li>${t('ความสว่างเรียงทิศทาง','Monotonic lightness')}: ${n.allMonotonic?'PASS':'REVIEW'}</li><li>${t('ขอบเขตห้ามม่วงและน้ำตาลตามตัวตรวจ','Numerical purple/brown exclusion gates')}: ${n.allBannedHuePass?'PASS':'REVIEW'}</li><li>${t('สีในช่วง clay ที่ตัวตรวจแจ้งให้ดูเพิ่ม','Samples flagged for clay-band visual review')}: ${(n.clayWarnings||[]).length}</li></ul><p>${t('ผลตัวเลขเป็นหลักฐานประกอบการออกแบบ ไม่ใช่การรับรองว่าทุกคนจะแยกได้ทุกคู่ สเกลที่ความหมายใกล้กันยังต้องมีชื่อ หน่วย และตัวหารกำกับ','Numerical checks support the design; they do not prove every viewer can distinguish every pair. Related scales still need names, units and denominators.')}</p><p>${t('คู่ที่ยังต้องดูเพิ่ม: density.area/heat, count/water และ activity/price; dark risk ยังใช้แซลมอนอ่อนที่ค่าสูง จึงต้องดูความรู้สึกเร่งด่วนด้วย ส่วน dark delta/tradeoff ลดความสดเข้าจุดกลางเร็วเพื่อไม่ให้เกิดสีที่สี่','Review remains for density.area/heat, count/water and activity/price. Dark risk still reaches pale salmon at high values, so urgency needs judgement. Dark delta/trade-off fade to neutral early to avoid a fourth hue.')}</p><p>${t('การจำลอง Deuteranopia ใช้เมทริกซ์ Machado ระดับเต็ม เป็นการจำลองบนหน้าจอ ไม่ใช่การทดสอบกับผู้ใช้จริง','Deuteranopia uses the full-severity Machado matrix. It is a screen simulation, not a study with users.')}</p><p><a href="https://colorbrewer2.org/learnmore/schemes.html" target="_blank" rel="noopener">ColorBrewer · ${t('ชนิดของสเกล','scheme types')}</a> · <a href="https://www.nature.com/articles/s41467-020-19160-7" target="_blank" rel="noopener">Crameri et al. · colour and data</a> · <a href="https://github.com/njsmith/colorspacious/blob/master/colorspacious/cvd.py" target="_blank" rel="noopener">Machado / Colorspacious</a></p><p><code>${esc(D.candidate.buildId)}</code></p>`;}
 function render(){document.documentElement.lang=S.lang;document.documentElement.dataset.theme=S.theme;document.body.className='vision-'+S.vision;document.querySelectorAll('[data-th][data-en]').forEach(e=>e.innerHTML=e.dataset[S.lang]);$('#language').value=S.lang;$('#theme').value=S.theme;$('#classes').value=S.n;$('#vision').value=S.vision;$('#family').innerHTML=ids.map(id=>`<option value="${id}">${esc(name(id))}</option>`).join('');$('#family').value=S.family;palette();compare();collisions();library();quality();syncURL();}
 for(const[id,key]of[['language','lang'],['theme','theme'],['family','family'],['classes','n'],['vision','vision']])$('#'+id).addEventListener('change',e=>{S[key]=key==='n'?+e.target.value:e.target.value;render();});
 $('#all-families').addEventListener('click',e=>{const b=e.target.closest('[data-family]');if(b){S.family=b.dataset.family;render();$('#compare').scrollIntoView({behavior:'auto'});$('#family').focus({preventScroll:true});}});
 render();window.STORY_REVIEW={state:S,record,data:D};
})();
