(function(){
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const ramp=(colors,cls='',label='ช่วงสี')=>`<div class="ramp visual-color ${cls}" role="img" aria-label="${esc(label)}">${colors.map(h=>`<i style="background:${h}"></i>`).join('')}</div>`;
 const effective=(scale,requested)=>scale.warm?([9,7,5,3].find(n=>n<=requested&&scale.themes.dark.options[n].separationPass)??2):requested;
 const chosen=(scale,requested)=>({requested,count:effective(scale,requested),changed:effective(scale,requested)!==requested});
 const labels=n=>Array.from({length:n},(_,i)=>`${Math.round(i*100/n)}–${i===n-1?'100':'<'+Math.round((i+1)*100/n)}`);
 const bars=[8,21,17,38,47,62,55,76,88,100,91,71];
 function barChart(colors){return `<div class="bar-chart visual-color" role="img" aria-label="ข้อมูลตัวอย่าง 12 ค่า: ${bars.join(', ')} ดัชนี 0 ถึง 100">${bars.map(v=>`<div class="bar-column"><b>${v}</b><i style="height:${v}%;background:${colors[Math.min(colors.length-1,Math.floor(v*colors.length/101))]}"></i></div>`).join('')}</div><div class="class-key">${colors.map((h,i)=>`<span><i class="visual-color" style="background:${h}"></i>${labels(colors.length)[i]}</span>`).join('')}</div>`;}
 function panel(scale,theme,request,count){const t=scale.themes[theme],before=t.options[request],after=t.options[count];return `<article class="theme-sample" data-sample-theme="${theme}" data-surface="featured-${theme}" ${scale.kind==='sequential'?`data-scale-family="${esc(scale.id)}"`:''}><div class="panel-head"><h3>${theme==='light'?'บนพื้นสว่าง':'บนพื้นมืด'}</h3><span>${theme.toUpperCase()} THEME</span></div><div class="ramp-heading"><span>ช่วงสีที่ใช้ได้</span><span>${t.lut.length} ขั้น${t.range==='mid-high'?' · mid → high':''}</span></div>${ramp(t.lut,'','ช่วงสี '+scale.label+' '+theme)}<div class="legend-extremes"><span>${scale.kind==='diverging'?'ลบ · ต่ำกว่าฐาน':'น้อย'}</span>${scale.kind==='diverging'?'<span>0 · ฐานอ้างอิง</span>':''}<span>${scale.kind==='diverging'?'บวก · สูงกว่าฐาน':'มาก'}</span></div><div class="ramp-heading"><span>ก่อนปรับ · ที่ขอ ${request} ระดับ</span><span>ห่างต่ำสุด ${before.minStep.toFixed(2)}</span></div>${ramp(before.hex,'discrete bad-ramp',`ก่อนปรับ ${request} ระดับ`)}<div class="ramp-heading"><strong>หลังปรับ · ใช้ ${count} ระดับ</strong><span>${count<request?'ลดจำนวนระดับ':'คงจำนวนระดับ'}</span></div>${ramp(after.hex,'discrete',`หลังปรับ ${count} ระดับ`)}<div class="metric"><span>ระยะสีติดกันต่ำสุด · ΔE</span><strong>${after.minStep.toFixed(2)}${scale.warm&&theme==='dark'?' / ≥ 2.2':''}</strong></div><div class="comparison-divider"></div><div class="chart-head"><span>ทดลองกับค่าข้อมูลเดิม</span><span>ข้อมูลสมมติ · ดัชนี 0–100</span></div>${barChart(after.hex)}</article>`;}
 function stage(D,id,request){const s=D.scales.find(s=>s.id===id),c=chosen(s,request);const msg=c.changed?`เลือก ${request} ระดับแล้วสีในธีมมืดชิดกันเกินไป จึงใช้ <strong>${c.count} ระดับในทั้งสองธีม</strong> เพื่อคงช่วงตัวเลขและ legend เดียวกัน`:s.warm?`ใช้ <strong>${c.count} ระดับได้ทั้งสองธีม</strong> ธีมมืดใช้ช่วง mid → high ตามข้อกำหนดปัจจุบัน`:`คง <strong>${c.count} ระดับในทั้งสองธีม</strong> เลือกตระกูลตามความหมายและหน่วยของข้อมูล`;return `<div class="result-note" role="status"><span class="note-mark">${c.changed?`${request} → ${c.count}`:`${c.count} ระดับ`}</span><div>${msg}<br><span class="small muted">${esc(s.meaning)}${s.kind==='diverging'?' · ตัวอย่างนี้ใช้ 0 เป็นฐานอ้างอิง':''}</span></div></div><div class="preview-grid">${panel(s,'light',request,c.count)}${panel(s,'dark',request,c.count)}</div><p class="comparison-note">ค่าข้อมูลยังเดิม เปลี่ยนเฉพาะวิธีแบ่งชั้นสี · ${s.warm?'เกณฑ์ 2.2 ใช้ตรวจสเกลอุ่นในธีมมืด':'ค่า ΔE แสดงเพื่อเปรียบเทียบ ไม่ใช่เกณฑ์รับรองใหม่'} · ${c.changed?'ช่วงตัวเลขของแต่ละชั้นเปลี่ยนตามจำนวนระดับ ต้องทบทวนก่อนใช้กับข้อมูลจริง':'การจำแนกในตัวอย่างแบ่งช่วง 0–100 เท่า ๆ กัน'}</p>`;}
 function exactTable(D,id,request){const s=D.scales.find(s=>s.id===id),n=effective(s,request);return `<p class="disclosure-note">${esc(s.id)} · ${n} ระดับ · ค่าทุกระดับสร้างจากวิธีคำนวณของแพ็กเกจเดียวกับแถบสีด้านบน</p><div class="table-scroll"><table><thead><tr><th>ช่วงตัวอย่าง</th><th>พื้นสว่าง</th><th>พื้นมืด</th></tr></thead><tbody>${s.themes.light.options[n].hex.map((h,i)=>`<tr><th>${labels(n)[i]}</th><td><i class="swatch-inline visual-color" style="background:${h}"></i><code>${h}</code></td><td><i class="swatch-inline visual-color" style="background:${s.themes.dark.options[n].hex[i]}"></i><code>${s.themes.dark.options[n].hex[i]}</code></td></tr>`).join('')}</tbody></table></div><p class="disclosure-note">สี light และ diverging บางช่วงยังอยู่ในหน้าต่างสีที่ระบบแจ้งเตือน รายละเอียดอยู่ในตารางช่วงสีทั้งหมดด้านล่าง การตรวจผ่านไม่ได้หมายความว่าไม่มีโทนน้ำตาลเหลืออยู่เลย</p>`;}
 function library(D){return D.scales.map(s=>`<article class="family-card" id="family-${s.id.replaceAll('.','-')}"><h3>${esc(s.label)}</h3><p><code>${s.id}</code> · ${s.kind==='sequential'?'น้อย → มาก':'สองทิศทาง'}</p>${['light','dark'].map(theme=>`<div class="theme-sample" data-sample-theme="${theme}"><div class="mini-label"><span>${theme}</span><span>${s.themes[theme].range==='mid-high'?'mid → high':'ช่วงเต็ม'}</span></div>${ramp(s.themes[theme].lut,'small-ramp',s.label+' '+theme)}</div>`).join('')}<button type="button" data-family="${s.id}">ทดลองสเกลนี้ ↗</button></article>`).join('');}
 function fullTables(D){return D.scales.map(s=>`<details class="details"><summary>${esc(s.label)} · <code>${s.id}</code></summary><div class="details-body"><p class="disclosure-note">${esc(s.meaning)} · ${esc(s.unit)} · ${s.kind==='diverging'?'ค่ากลางต้องมีความหมายจริง':'น้อย → มาก'}</p>${['light','dark'].map(theme=>`<details class="details"><summary>${theme} · ทุก ${s.themes[theme].lut.length} ขั้นที่ใช้ได้</summary><div class="details-body"><div class="table-scroll"><table><thead><tr><th>ตำแหน่ง</th><th>สี</th><th>หมายเหตุ hue</th></tr></thead><tbody>${s.themes[theme].lut.map((h,i)=>{const finding=s.themes[theme].hueWarnings.find(w=>w.index===i);return `<tr><th>${i} / ${s.themes[theme].lut.length-1}</th><td><i class="swatch-inline visual-color" style="background:${h}"></i><code>${h}</code></td><td>${finding?esc([...new Set(finding.findings.map(f=>f.window))].join(', '))+' · แจ้งเตือน':'ไม่พบ'}</td></tr>`;}).join('')}</tbody></table></div></div></details>`).join('')}</div></details>`).join('');}
 function gradient(D,id){const g=D.gradients.find(g=>g.id===id),deep=g.name==='measure.deep'||g.name==='ground.current';return `<div class="atmosphere-art visual-color" style="background:${g.css};color:${deep?'var(--ldm-foundation-surface-raised-light)':'var(--ldm-foundation-text-primary-light)'}"><div class="art-label">LANDOMETER / ${esc(g.name)}</div><div><h3>มองเห็นบริบท<br>ก่อนลงมือเปลี่ยนแปลง</h3><p>ใช้บรรยากาศช่วยเปิดเรื่องและจัดจังหวะ<br>ให้ข้อมูลเป็นสิ่งที่ผู้อ่านเห็นชัดเสมอ</p></div><div class="art-bottom"><span>ตัวอย่างพื้นผิว · ไม่ใช้เข้ารหัสข้อมูล</span><div class="art-lines" aria-hidden="true">${[13,26,19,42,32].map(v=>`<i style="height:${v}px"></i>`).join('')}</div></div></div><div class="gradient-spec">${g.stops.map(s=>`<span class="stop"><i class="visual-color" style="background:${s.hex}"></i><code>${s.hex}</code> · ${s.at}%</span>`).join('')}</div><p class="disclosure-note">ทิศทาง 135° · คงสูตรเดิมจาก 0.9.1 · ${esc(g.purpose)}</p>`;}
 function symbol(cue){return {circle:'●',square:'■',triangle:'▲',diamond:'◆',cross:'×',star:'✦',hexagon:'⬡',pentagon:'⬟',dash:'━',plus:'+',ring:'○','triangle-down':'▼',x:'×'}[cue]??'◇';}
 function categories(D,variant){return ['light','dark'].map(theme=>`<article class="theme-sample" data-sample-theme="${theme}"><div class="panel-head"><h3>${theme==='light'?'พื้นสว่าง':'พื้นมืด'}</h3><span>${variant.toUpperCase()}</span></div>${D.series.map((s,i)=>`<div class="series-row"><span class="series-symbol" style="color:${s[theme].ink}" aria-hidden="true">${symbol(s.cue)}</span><div class="series-bar visual-color" style="background:${s[theme][variant==='soft'?'fill':'vivid']}"></div><span class="series-name">${String(i+1).padStart(2,'0')} ${esc(s.name)}</span></div>`).join('')}<div class="line-example"><p class="small" style="color:var(--panel-meta)">เส้นบางหมวด 02 / 03 · เพิ่มรูปแบบเส้นและป้ายชื่อ</p><svg viewBox="0 0 440 104" role="img" aria-label="เส้นหมวด02ใช้เส้นทึบกับสี่เหลี่ยม เส้นหมวด03ใช้เส้นประกับสามเหลี่ยม"><path d="M15 77L90 55L165 63L240 31L315 45L410 18" fill="none" stroke="${D.series[1][theme].ink}" stroke-width="2"/><path d="M15 88L90 80L165 40L240 64L315 61L410 39" fill="none" stroke="${D.series[2][theme].ink}" stroke-width="2" stroke-dasharray="7 5"/><rect x="86" y="51" width="8" height="8" fill="${D.series[1][theme].ink}"/><path d="M165 35l5 9h-10z" fill="${D.series[2][theme].ink}"/></svg><div class="line-legend"><span style="color:${D.series[1][theme].ink}"><i></i>■ 02 apricot</span><span style="color:${D.series[2][theme].ink}"><i class="dashed"></i>▲ 03 yellow</span></div></div></article>`).join('');}
 function inventory(D){return D.inventory.map(r=>`<div class="role-item">${r.id==='brand.logoCyan'||r.id==='brand.logoGray'?'<p>เฉพาะไฟล์โลโก้</p>':`<i class="visual-color" style="background:${r.hex}"></i>`}<code>${esc(r.id)}</code><span>${r.hex}</span></div>`).join('');}
 globalThis.PreviewRender={esc,ramp,effective,stage,exactTable,library,fullTables,gradient,categories,inventory};
})();
